title: Spudnik
email: comrades@spudnik.io
description: >-
  A robust Discord chat bot focused on
  guild management and adding interesting
  and useful functionality to your server.
baseurl: ""
url: "https://docs.spudnik.io"
github_username:  Spudnik-Group
repository: Spudnik-Group/Spudnik
markdown: kramdown
plugins:
  - jekyll-feed